//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VREI
{
    using System;
    using System.Collections.Generic;
    
    public partial class activitypic
    {
        public int Id { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public string ImageUrl { get; set; }
        public string ImageDescription { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> DateTimeEdited { get; set; }
    
        public virtual activity activity { get; set; }
    }
}
