//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VREI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbo_vreiEntities : DbContext
    {
        public dbo_vreiEntities()
            : base("name=dbo_vreiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity> activities { get; set; }
        public virtual DbSet<activitypic> activitypics { get; set; }
        public virtual DbSet<homepageslider> homepagesliders { get; set; }
        public virtual DbSet<pagecontent> pagecontents { get; set; }
    }
}
